# docker run -d --rm --name -p 27017:27017 -v mongodbdata:/data/db mongo
version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672 # to consom msg and publish msg to rabbitMQ
      - 15672:15672 # to call rabbit MQ Portal
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
volumes:
  mongodbdata:
  rabbitmqdata:
